// <auto-generated />
namespace Transparencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nuevosModulos4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuevosModulos4));
        
        string IMigrationMetadata.Id
        {
            get { return "202108031707397_nuevosModulos4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
